package demo.driver.domain;

public enum DriverEventType {
    DRIVER_CREATED,
    DRIVER_WENT_ONLINE,
    DRIVER_WENT_OFFLINE,
    LOCATION_UPDATED,
    ACCOUNT_ACTIVATED,
    ORDER_DELIVERED,
    ACCOUNT_SUSPENDED,
    ACCEPTED_ORDER_REQUEST,
    DECLINED_ORDER_REQUEST,
    RECEIVED_ORDER_REQUEST,
    ORDER_PICKED_UP,
    ORDER_DELIVERING
}
